### ISSUE TITLE
Installed IPv6 routes are not always added to kernel routing table

### ISSUE THREAD

**Issue by mweinelt** [jech/babeld#14] opened 2018-06-12 19:23 UTC
I'm currently on babeld 1.8.2 (debian/1.8.1-1-3-gc48aa52) and I'm sometimes missing IPv6 routes in the kernel routing table, which babel tells me are installed.

```
# echo "dump" | timeout 1 nc :: 33123 | grep "installed yes"
add route 560fbc5dae20 prefix 172.23.42.1/32 from 0.0.0.0/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5d7180 prefix 172.23.42.2/32 from 0.0.0.0/0 installed yes id c4:34:36:e4:f6:42:71:a0 metric 96 refmetric 0 via fe80::2 if wg-snafu
add route 560fbc5dcba0 prefix 172.23.42.8/32 from 0.0.0.0/0 installed yes id 02:0d:b9:ff:fe:49:cc:f8 metric 96 refmetric 0 via fe80::1 if wg-io
add route 560fbc5dbd30 prefix 172.23.42.10/32 from 0.0.0.0/0 installed yes id 2a:d2:44:ff:fe:9d:d2:bf metric 116 refmetric 0 via fe80::2 if wg-eris
add route 560fbc5dcce0 prefix 172.23.42.64/26 from 0.0.0.0/0 installed yes id 02:0d:b9:ff:fe:49:cc:f8 metric 96 refmetric 0 via fe80::1 if wg-io
add route 560fbc5dcd80 prefix 172.23.42.128/26 from 0.0.0.0/0 installed yes id 02:0d:b9:ff:fe:49:cc:f8 metric 96 refmetric 0 via fe80::1 if wg-io
add route 560fbc5daf90 prefix 172.23.42.226/31 from 0.0.0.0/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5db030 prefix 172.23.42.238/31 from 0.0.0.0/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5db0d0 prefix 172.23.42.240/31 from 0.0.0.0/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5dc880 prefix fd42:23:42:100::/64 from ::/0 installed yes id 02:0d:b9:ff:fe:49:cc:f8 metric 96 refmetric 0 via fe80::1 if wg-io
add route 560fbc5dc920 prefix fd42:23:42:110::/64 from ::/0 installed yes id 02:0d:b9:ff:fe:49:cc:f8 metric 96 refmetric 0 via fe80::1 if wg-io
add route 560fbc5dad80 prefix fd42:23:42:b100::/56 from ::/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5dc010 prefix fd42:23:42:b200::/56 from ::/0 installed yes id c4:34:36:e4:f6:42:71:a0 metric 96 refmetric 0 via fe80::2 if wg-snafu
add route 560fbc5dcb40 prefix fd42:23:42:b800::/56 from ::/0 installed yes id 02:0d:b9:ff:fe:49:cc:f8 metric 96 refmetric 0 via fe80::1 if wg-io
add route 560fbc5dbcd0 prefix fd42:23:42:ba00::1/128 from ::/0 installed yes id 2a:d2:44:ff:fe:9d:d2:bf metric 116 refmetric 0 via fe80::2 if wg-eris
add route 560fbc5db670 prefix fd42:23:42:ff01::/64 from ::/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5db710 prefix fd42:23:42:ff07::/64 from ::/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
add route 560fbc5dc9c0 prefix fd42:23:42:ff08::/64 from ::/0 installed yes id d4:57:67:c3:ff:0b:d5:f9 metric 96 refmetric 0 via fe80::2 if wg-glitch
```
That is 9 IPv4 and 9 IPv6 routes which are supposed to be installed to the kernel routing table.

The export-table is configured as follows:
```
export-table 100  # igp
```

However only one of the IPv6 routes is actually installed.
```
# ip -6 r s t 100 
fd42:23:42:ff07::/64 via fe80::2 dev wg-glitch proto babel metric 1024 onlink pref medium
```

While all of the IPv4 routes are properly installed:
```
# ip -4 r s t 100 
172.23.42.1 via 172.23.42.231 dev wg-glitch proto babel onlink 
172.23.42.2 via 172.23.42.233 dev wg-snafu proto babel onlink 
172.23.42.8 via 172.23.42.224 dev wg-io proto babel onlink 
172.23.42.10 via 172.23.42.235 dev wg-eris proto babel onlink 
172.23.42.64/26 via 172.23.42.224 dev wg-io proto babel onlink 
172.23.42.128/26 via 172.23.42.224 dev wg-io proto babel onlink 
172.23.42.226/31 via 172.23.42.231 dev wg-glitch proto babel onlink 
172.23.42.238/31 via 172.23.42.231 dev wg-glitch proto babel onlink 
172.23.42.240/31 via 172.23.42.231 dev wg-glitch proto babel onlink 
```

Possibly related log output, summed up by process and message:
```
# journalctl -u babeld | cut -d' ' -f5- | sort | uniq -c
      1 Thu 2018-06-07 19:32:31 CEST, end at Tue 2018-06-12 21:19:33 CEST. --
      7 babeld[1976]: kernel_route(ADD): No such device
      2 babeld[1976]: kernel_route(FLUSH): No such process
     85 babeld[1976]: kernel_route(MODIFY metric): No such device
  27413 babeld[1976]: send: Destination address required
     66 babeld[21726]: kernel_route(ADD): No such device
     20 babeld[21726]: kernel_route(FLUSH): No such process
    589 babeld[21726]: kernel_route(MODIFY metric): No such device
  85511 babeld[21726]: send: Destination address required
      1 systemd[1]: Started Babel routing daemon.
      1 systemd[1]: Stopped Babel routing daemon.
      1 systemd[1]: Stopping Babel routing daemon...
```

This happens after some hours of babeld running. As soon as I restart babeld all routes are back as they should:

```
# ip -6 r s t 100
fd42:23:42:100::/64 via fe80::1 dev wg-io proto babel metric 1024 onlink pref medium
fd42:23:42:110::/64 via fe80::1 dev wg-io proto babel metric 1024 onlink pref medium
fd42:23:42:b100::/56 via fe80::2 dev wg-glitch proto babel metric 1024 onlink pref medium
fd42:23:42:b200::/56 via fe80::2 dev wg-snafu proto babel metric 1024 onlink pref medium
fd42:23:42:b800::/56 via fe80::1 dev wg-io proto babel metric 1024 onlink pref medium
fd42:23:42:ba00::1 via fe80::2 dev wg-eris proto babel metric 1024 onlink pref medium
fd42:23:42:ff01::/64 via fe80::1 dev wg-io proto babel metric 1024 onlink pref medium
fd42:23:42:ff07::/64 via fe80::2 dev wg-snafu proto babel metric 1024 onlink pref medium
fd42:23:42:ff08::/64 via fe80::2 dev wg-glitch proto babel metric 1024 onlink pref medium
```

**Comment by jech** [comment] 2018-06-22 22:05
Are the interfaces disappearing and reappearing later?  There's a race condition in babeld that could cause these symptoms if an interface disappeared and reappeared under the same name within 30 seconds.

**Comment by mweinelt** [comment] 2018-06-22 23:38
That (ifdown, rmmod, modprobe, ifup) happens sometimes, when I upgrade wireguard, but I also loose routes without touching any of the links on the server.

**Comment by jech** [comment] 2018-06-23 11:18
Please let me know if the following patch makes the problem go away.  (It's a workaround, not a proper fix.)

```
diff --git a/babeld.c b/babeld.c
index 402230c..cafc143 100644
--- a/babeld.c
+++ b/babeld.c
@@ -558,7 +558,7 @@ main(int argc, char **argv)
     kernel_addr_changed = 0;
     kernel_dump_time = now.tv_sec + roughly(30);
     schedule_neighbours_check(5000, 1);
-    schedule_interfaces_check(30000, 1);
+    schedule_interfaces_check(100, 1);
     expiry_time = now.tv_sec + roughly(30);
     source_expiry_time = now.tv_sec + roughly(300);
 
@@ -740,7 +740,7 @@ main(int argc, char **argv)
 
         if(timeval_compare(&check_interfaces_timeout, &now) < 0) {
             check_interfaces();
-            schedule_interfaces_check(30000, 1);
+            schedule_interfaces_check(100, 1);
         }
 
         if(now.tv_sec >= expiry_time) {
```

**Comment by mweinelt** [comment] 2018-06-23 23:43
It's weird. I watched that happen two evenings in a row when I reported the issue. The kernel rt currently stays populated correctly. When that changes again I'll test your patch.

**Comment by jech** [comment] 2018-07-01 22:50
Either something is flushing the routes, or the interfaces go down-up without babeld noticing, or there's a bug somewhere.  Sorry I cannot be of more help.

**Comment by mweinelt** [comment] 2018-07-01 23:41
Is something about routing table 100 significant to babel?

I'm running bird alongside babeld on that machine, but it does not touch igp routing tables and only does static announcements.

I'm using `ip monitor link` to rule out link flaps, none happen.

**Comment by christf** [comment] 2018-07-04 21:56
babeld is checking whether an interface has changed based on an interval. If the interface is down and back up in a time that is shorter than the interval, thie behavior would occur.

I am not quite sure about a proper fix. It seems to me that it could be enough to add an additional check to kernel_netlink.c in netlink_read(). There it could be checked whether the current event is of nlmsg_type RTM_NEWLINK|RTM_DELLINK|RTM_CHANGELINK and if it is, the interface check should be triggered as it is.

**Comment by jech** [comment] 2018-07-05 00:31
> I am not quite sure about a proper fix. It seems to me that it could be enough
> to add an additional check to kernel_netlink.c in netlink_read(). There it
> could be checked whether the current event is of nlmsg_type
> RTM_NEWLINK|RTM_DELLINK|RTM_CHANGELINK and if it is, the interface check
> should be triggered as it is.

I'll be grateful if you test whether that fixes your issue.

**Comment by christf** [comment] 2018-07-15 13:50
So I prepared a patch that works as described above. While it does not fix
@mweinelt  issue, I still feel this is the right approach to detect interface
changes as it reduces the likelyhood of babeld not noticing an ifup/ifdown. I
was able to verify this with a pair of veth and could see the check being
triggered. Unfortunately the interface_check is also scheduled when there is no ip address assigned to an interface so we cannot entirely get rid of the scheduled check yet before reworking check_link_local_addresses() in interface.c. I added FIXME comments for this in my patch.

In this issue, we are dealing with a point-to-point interface which is
considered "UP" all the time while the remote endpoint flaps. Due to this, the
kernel apparently never emits a RTM_DELLINK/RTM_NEWLINK,
To solve this, we need to find out which signal can be emitted by the kernel in
this situation and subscribe to it. At this point I am not sure there is a
generic solution as I have not worked with point-to-point interfaces
previously. That being said, using wireguard in conjunction with babeld is
something that the freifunk community has wanted to do for a while. Without
solving this issue, that cannot be done.

Interestingly the routes get lost even though the interface is always up. My
expectation would be that the kernel retains routes while the interface is up.
The fact that these routes get lost is surprising me.

**Comment by m13253** [comment] 2018-07-23 08:50
I confirm this problem with a setup of \[OpenVPN TCP -> [WireGuard Mesh -> VxLAN](https://github.com/m13253/VxWireguard-Generator)\].

I run Babeld on VxLAN interface. Although the upper two layers does not change, the OpenVPN goes up and down frequently.

To test the bug, I typed:
```bash
sudo systemctl stop openvpn-client@vpn.service
sleep 10
sudo systemctl start openvpn-client@vpn.service
tail -f /var/log/babeld.log  # Debian babeld package does not go through systemd journal
```

I see babeld printing an infinite loop of
```
kernel_route(ADD): No such device
```
with a CPU utilization of 80%-100%.

This is weird, since OpenVPN does not flush routes on the upper layers. Babeld is interfered by an interface it is not running on.

My babeld version: `babeld-1.8.2-1-g8cbc75d`.
To get this version, I first installed babeld package from Debian sid repo, then compiled the latest code and replaced the binary.

**Comment by m13253** [comment] 2018-07-23 09:36
I captured a log of bootstrapping my Babel instance (with all underlying links up and stable):

![/var/log/babeld.log](https://user-images.githubusercontent.com/1808930/43068377-9cbb93a2-8ead-11e8-883c-7587a1a467dc.png)
(Please tell me if I should paste text instead of attaching a PNG here next time)

It seems that the problem happens at the first second, even without any link up / down.

---

A detailed trace with `debug 3` shows:
```
Received update/prefix for 2a0d:2********4d/128 from fe80::90f8:f6ff:feb7:4b4d on vx-wg-sc.
install_route(2a0d:2********4d/128 from ::/0)
kernel_route: add 2a0d:2********4d/128 from ::/0 table 254 metric 65535 dev 6 nexthop fe80::90f8:f6ff:feb7:
4b4d
Sending seqno 41062 from address 0x56534d99f2d0 (talk)
Netlink message: {seq:41062}netlink_read: No such device
kernel_route(ADD): No such device
```
I checked that dev 6 is there:
```
6: vx-wg-sc: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1966 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether ea:78:41:57:48:78 brd ff:ff:ff:ff:ff:ff
```

Hmm, it's weird.

**Comment by christf** [comment] 2018-07-27 13:18
I am seeing the same log with 1.8.2. This completely fills server logs here. Interestingly this did not occur with 1.8.0.

**Comment by christf** [comment] 2018-08-02 13:46
nltrace reveals this:
```
115999 netlink send(4):
116000 Setting msg proto to 0
116001 --------------------------   BEGIN NETLINK MESSAGE ---------------------------
116002   [NETLINK HEADER] 16 octets
116003     .nlmsg_len = 56
116004     .type = 24 <route/route::new>
116005     .flags = 1541 <REQUEST,ACK,MATCH,ATOMIC>
116006     .seq = 3595
116007     .port = 0
116008   [PAYLOAD] 12 octets
116009     0a 80 00 00 0a 2a 00 07 04 00 00 00             .....*......
116010   [ATTR 01] 16 octets
116011     fe c0 00 00 00 00 00 00 f2 98 9d ff fe d3 2d 15 ..............-.
116012   [ATTR 06] 4 octets
116013     ff ff ff ff                                     ....
116014 ---------------------------  END NETLINK MESSAGE   ---------------------------
116015 netlink recv(4):
116016 Setting msg proto to 0
116017 --------------------------   BEGIN NETLINK MESSAGE ---------------------------
116018   [NETLINK HEADER] 16 octets
116019     .nlmsg_len = 76
116020     .type = 2 <ERROR>
116021     .flags = 0 <>
116022     .seq = 3595
116023     .port = 2240
116024   [ERRORMSG] 20 octets
116025     .error = -19 "No such device"
116026   [ORIGINAL MESSAGE] 16 octets
116027     .nlmsg_len = 16
116028     .type = 24 <0x18>
116029     .flags = 1541 <REQUEST,ACK,MATCH,ATOMIC>
116030     .seq = 3595
116031     .port = 0
116032 ---------------------------  END NETLINK MESSAGE   ---------------------------
116033 nl_recvmsgs_report() returns error
116034 kernel_route(ADD): No such device
116035 netlink recv(5):
116036 Setting msg proto to 0

```

**Comment by christf** [comment] 2018-08-02 15:23
toggline reflect-kernel-metric seems to impact the "No such device" message. I cannot see "No such device" when reflect-kernel-metric is not set in the config file.

I can still see "No such process"
```
infeasible update for installed route to fec0::3275:12ff:fefd:ab63/128 (ea:94:f6:ff:fe:40:c1:aa 38474 16652 -> ea:94:f6:ff:fe:40:c1:aa 38474 16652).
Received update/prefix for fec0::6257:18ff:fe88:d7f9/128 from fe80::a800:ff:fed5:4ced on ens14.
Received update/prefix for fec0::8ef5:a3ff:fee3:b509/128 from fe80::a800:ff:fed5:4ced on ens14.
Received update/prefix for fec0::f298:9dff:fed3:2d15/128 from fe80::a800:ff:fed5:4ced on ens14.
Received update/prefix/id for 2a06:8187:fbab:1:f29f:c2ff:fe67:c676/128 from fe80::a800:ff:fed5:4ced on ens14.
Received router-id fa:1a:67:ff:fe:a4:95:c5 from fe80::a800:ff:fed5:4ced on ens14.
Received update/prefix for 2a06:8187:fbab:1:fa1a:67ff:fea4:95c6/128 from fe80::a800:ff:fed5:4ced on ens14.
switch_routes(2a06:8187:fbab:1:fa1a:67ff:fea4:95c6/128 from ::/0)
kernel_route: flush 2a06:8187:fbab:1:fa1a:67ff:fea4:95c6/128 from ::/0 table 10 metric 0 dev 3 nexthop fe80::a800:ff:fed5:4ced
Sending seqno 8025 from address 0x56019dfac2d0 (talk)
Netlink message: {seq:8025}netlink_read: No such process
kernel_route: add 2a06:8187:fbab:1:fa1a:67ff:fea4:95c6/128 from ::/0 table 10 metric 0 dev 7 nexthop fe80::fc67:aaff:feea:55c7
Sending seqno 8026 from address 0x56019dfac2d0 (talk)
Netlink message: {seq:8026}netlink_read: File exists
RTT to fe80::a800:ff:fed5:4ced on ens14 sample result: 666 us.
```

**Comment by christf** [comment] 2018-08-10 16:56
it seems that I can reproduce this using ip route add. If I add a route, omitting a device I get the same error message. If I do not omit the device, another attribute (ATTR04) containing the device ID is added to the netlink request.

**Comment by m13253** [comment] 2018-08-10 17:15
Also observed route missing problem with IPv4. Restarting babeld on the affected intermediate router solved the problem.
Hard to capture logs as evidence because the problem goes away as soon as I restarted it with another verbosity.

**Comment by christf** [comment] 2018-08-12 08:01
could you try if the issue persists with https://github.com/christf/babeld/tree/FIX_nosuchdevice

**Comment by m13253** [comment] 2018-08-13 07:59
> could you try if the issue persists with https://github.com/christf/babeld/tree/FIX_nosuchdevice or #19

Seems the problem has gone away with the patch. Thanks! 🎉
I will continue to test the network for several days to see if the problem is really gone.

**Comment by mweinelt** [comment] 2018-08-13 21:03
Looks go here as well, thanks!

**Comment by m13253** [comment] 2018-08-15 22:47
> could you try if the issue persists with https://github.com/christf/babeld/tree/FIX_nosuchdevice or #19

Patch tested on Linux 4.17.0 and 4.14.52, network with 7 nodes.
Eliminated "no such device" errors during last 3 days.

Has anyone tested compatibility with older kernels?

**Comment by christf** [comment] 2018-08-17 19:16
I have this running with 15 nodes where 2 of them run kernel 4.14 and the rest runs 4.4

**Comment by m13253** [comment] 2018-09-16 11:46
@jech The patch is already available. Would you please merge it?
We've been missing you for weeks :-)

**Comment by jech** [comment] 2018-09-16 20:14
I cannot merge it before I test it myself -- this means having access to
my lab, which was not the case during the summer.

I'm now back at the lab, but too busy to rebuild my network.  Sorry for
the delay, I'll try to get my act together ASAP.

**Closed** 2018-09-19 08:08 UTC
